### PR TITLE
Add support for setting msx transpiler options

### PR DESCRIPTION
**Pull request by ketan**
Add support for passing in transpiler options from a yaml file into MSXTransformer.

The supported options are - https://github.com/insin/msx/blob/v0.4.1/bin/msx#L45-L53

### CODE REVIEW

**Comment by mrsweaters** [comment]
@ketan This looks great! I'll merge it in if you update the documentation.

**Comment by ketan** [comment]
@mrsweaters - I did update the README - https://github.com/mrsweaters/mithril-rails/pull/11/files#diff-04c6e90faac2675aa89e2176d2eec7d8R70

**Comment by ketan** [comment]
Actually, I just realized that I missed pushing a commit. I'll rebase and let you know.

**Comment by ketan** [comment]
I rebased and updated the PR again. You can see the rendered documentation here - 
https://github.com/ketan/mithril-rails/tree/msx-rails-options#configuration

**Comment by ketan** [comment]
On second thought, it does not work as expected. A lot of these transforms are handled by [another script](https://github.com/insin/msx/blob/master/main.js#L96-L126) that has a bunch of dependencies. I'll submit another PR when this is well tested.

/cc @zabil

**Comment by mrsweaters** [comment]
@ketan Thanks for taking a deeper look into it.

**Pull request closed without merging**
